apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-httpbin-prefix
  namespace: apps
spec:
  stripPrefix:
    prefixes:
      - "/httpbin"
      - "/v1"
      - "/v2"

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers
  namespace: apps
spec:
  headers:
    customRequestHeaders:
      X-Custom-Request-Header: "/v2/translate"
    customResponseHeaders:
      X-Custom-Response-Header: "/v2/translate"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: waf
  namespace: apps
spec:
  plugin:
    coraza:
      crsEnabled: true
      directives:
        - SecRuleEngine On
        - SecRequestBodyAccess On
        - SecRequestBodyLimit 13107200
        - SecRequestBodyLimitAction Reject
        - SecRule ARGS_NAMES "@streq glossary_id" "id:1003,phase:2,deny,log,status:400,msg:'Blocked glossary_id'"