---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedApplication
metadata:
  name: traefik-mobile
  namespace: apps
spec:
  appId: traefik-mobile          
  owner: traefik 
  notes: "For IOS & Android clients"
  apiKeys:
    - secretName: traefik-mobile-key
      title: mobile-key

---

apiVersion: v1
kind: Secret
metadata:
  name: traefik-mobile-key
  namespace: apps
type: Opaque
data:
  # echo -n "secret-api-key" | openssl dgst -SHAKE256 -xoflen 64 | awk '{ print $2; }' | tr -d "\n" | base64 -w0
  key: MDYxN2VkOGIyNjY0YzI1YTFkZmQyNWU5ZjU5NGM3OTM1NmJjYjBiYTRlYTFmNmMzOWU4MTQwZGUwYThkOTE3NjExMDMwYzQ4NmFkNjI3NTRkZjc3MGIxM2FkOWU2OThhZDE2M2FhOGNhM2ZkYTE0YWRmYmFiNGI1YTgzN2UzMDI=

---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: traefik-subscription
  namespace: apps
spec:
  managedApplications:
    - name: "carlos-application"
    - name: "amer-application"
  apis:
    - name: httpbin-api
  apiPlan:
    name: httpbin-gold-plan
  weight: 10