name: Create Traefik IngressRoute CRD
description: Create a Traefik IngressRoute CRD with middleware section
inputs:
  - name: name
    description: Name of the IngressRoute
    required: true
  - name: namespace
    description: Namespace of the IngressRoute
    required: true
  - name: entryPoints
    description: Entry points for the IngressRoute (e.g. web)
    required: true
  - name: routes
    description: Routes for the IngressRoute (e.g. Host(`httpbin.apigateway.docker.localhost`))
    required: true
  - name: services
    description: Services for the IngressRoute (e.g. name: httpbin-svc, port: 8000)
    required: true

outputs:
  - name: crd
    value: |
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: ${name}
        namespace: ${namespace}
      spec:
        entryPoints:
          - ${entryPoints}
        routes:
          - match: ${routes}
            services:
              - name: ${services.name}
                port: ${services.port}
        middlewares:
          - name: jwt
            namespace: traefik
          - name: opa
            namespace: traefik
