apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ route }}`)
      services:
        - name: {{ service }}
          port: 8000
  middlewares:
    - name: jwt
      namespace: traefik
    - name: ratelimit
      namespace: traefik
