---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPortal
metadata:
  name: httpbin-portal
  namespace: apps
spec:
  title: HTTPBin Portal
  description: "API Portal for HTTPBin"
  trustedUrls:
    - http://portal.httpbin.localhost:8000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-portal
  namespace: apps
  annotations:
    hub.traefik.io/api-portal: httpbin-portal
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`portal.httpbin.localhost`)
    kind: Rule
    services:
    - name: apiportal
      namespace: traefik
      port: 9903
