---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin-route
  namespace: apps
  annotations:
    hub.traefik.io/api: httpbin-api
    hub.traefik.io/api-version: httpbin-default
spec:
  parentRefs:
    - name: web-gateway
  hostnames:
    - "httpbin.traefik.localhost"
    - "httpbin.traefik.cloud"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: httpbin-svc
          namespace: apps
          port: 8000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin-route-v2
  namespace: apps
  annotations:
    hub.traefik.io/api: httpbin-api
    hub.traefik.io/api-version: httpbin-v2
spec:
  parentRefs:
    - name: web-gateway
  hostnames:
    - "httpbin.traefik.localhost"
    - "httpbin.traefik.cloud"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
          headers:
            - name: "X-API-Version"
              value: "v2"
      backendRefs:
        - name: httpbin-svc
          namespace: apps
          port: 8000
---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: httpbin-default
  namespace: apps
spec:
  title: "HTTPBin API"
  description: "HTTPBin API OpenAPI spec"
  release: v1.0.0
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: http://httpbin.traefik.localhost:8000/
        - url: http://httpbin.traefik.cloud/
    operationSets:
      - name: default
        matchers:
          - pathPrefix: /
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: httpbin-v2
  namespace: apps
spec:
  title: "HTTPBin API"
  description: "HTTPBin API OpenAPI spec"
  release: v2.0.0
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: http://httpbin.traefik.localhost:8000/
        - url: http://httpbin.traefik.cloud/
    operationSets:
      - name: anything-only
        matchers:
          - pathPrefix: /anything
            methods:
              - GET
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: httpbin-api
  namespace: apps
spec:
  title: "HTTPBin API"
  description: "HTTPBin API OpenAPI spec"
  versions:
    - name: httpbin-default
    - name: httpbin-v2
