name: Traefik IngressRoute Generator

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of the IngressRoute
        required: true
      namespace:
        description: Namespace of the IngressRoute
        required: true
      route:
        description: Route of the IngressRoute
        required: true
      service:
        description: Service of the IngressRoute
        required: true

jobs:
  generate-ingressroute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate IngressRoute
        run: |
          echo "apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: ${{ github.event.inputs.name }}
            namespace: ${{ github.event.inputs.namespace }}
          spec:
            entryPoints:
              - web
            routes:
              - match: Host(`${{ github.event.inputs.route }}`)
                services:
                  - name: ${{ github.event.inputs.service }}
                    port: 8000
            middlewares:
              - name: jwt
                namespace: traefik
              - name: opa
                namespace: traefik" > ingressroute.yaml
      - name: Upload IngressRoute
        uses: actions/upload-artifact@v2
        with:
          name: ingressroute.yaml
          path: ingressroute.yaml
