name: Traefik IngressRoute Generator

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of the IngressRoute
        required: true
      namespace:
        description: Namespace of the IngressRoute
        required: true
      route:
        description: Route of the IngressRoute
        required: true
      service:
        description: Service of the IngressRoute
        required: true

permissions:
  contents: write

jobs:
  generate-ingressroute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: true
      - name: Generate IngressRoute
        run: |
          echo "apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: ${{ github.event.inputs.name }}
            namespace: ${{ github.event.inputs.namespace }}
          spec:
            entryPoints:
              - web
            routes:
              - match: Host(${github.event.inputs.route})
                services:
                  - name: ${{ github.event.inputs.service }}
                    port: 8000
            middlewares:
              - name: jwt
                namespace: traefik
              - name: opa
                namespace: traefik" > artifacts/${github.event.inputs.name}-ingressroute.yaml
      - name: Commit and push file
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add artifacts/${github.event.inputs.name}-ingressroute.yaml
          git commit -m "Upload ${github.event.inputs.name}-ingressroute.yaml"
          git push
