apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: apiops
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/apiaddicts`)
      services:
        - name: raspberry-svc
          port: 3002
      middlewares:
        - name: strip-raspberrypi-prefix
        - name: keycloak-jwt-authentication
        - name: waf
        - name: opa-allow-jwt-claim
          namespace: traefik
